backend:
  name: git-gateway
  branch: main   # si ta branche par défaut est "master", remplace par master

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Contenu du site"
    files:
      - file: "content/site.json"
        label: "Paramètres & Contenu"
        name: "site"
        fields:
          - label: "HERO"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Texte (lead)", name: "lead", widget: "text" }
          - label: "LIVRES"
            name: "books"
            widget: "object"
            fields:
              - label: "Imogene"
                name: "imogene"
                widget: "object"
                fields:
                  - { label: "Titre", name: "title", widget: "string" }
                  - { label: "Description", name: "desc", widget: "text" }
                  - { label: "Lien - Toutes plateformes", name: "all_platforms_url", widget: "string" }
                  - { label: "Lien - Amazon", name: "amazon_url", widget: "string" }
              - label: "Achille"
                name: "achille"
                widget: "object"
                fields:
                  - { label: "Titre", name: "title", widget: "string" }
                  - { label: "Description", name: "desc", widget: "text" }
                  - { label: "Lien - Toutes plateformes", name: "all_platforms_url", widget: "string" }
                  - { label: "Lien - Amazon", name: "amazon_url", widget: "string" }
              - label: "Ezra"
                name: "ezra"
                widget: "object"
                fields:
                  - { label: "Titre", name: "title", widget: "string" }
                  - { label: "Description", name: "desc", widget: "text" }
                  - { label: "Lien - Toutes plateformes", name: "all_platforms_url", widget: "string" }
                  - { label: "Lien - Amazon", name: "amazon_url", widget: "string" }
          - label: "EXTRAIT"
            name: "excerpt"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Texte", name: "text", widget: "text" }
          - label: "A PROPOS"
            name: "about"
            widget: "object"
            fields:
              - { label: "Texte", name: "text", widget: "text" }
          - label: "ASSETS"
            name: "assets"
            widget: "object"
            fields:
              - { label: "Image hero (URL)", name: "hero_image", widget: "string" }
              - { label: "Image extrait (URL)", name: "excerpt_image", widget: "string" }
              - { label: "Kit Presse (URL)", name: "presskit_url", widget: "string" }
